title: Store Framework - Español
tagline: A VTEX Store Framework automated course
description: >-
  Learning how to build a store using the Store Framework blocks language,
  powered by VTEX IO.
template:
  repo: store-framework-template
  name: store-framework
before:
  - type: createIssue
    title: Configuraciones básicas
    body: setup.md
steps:
  - title: Configuraciones básicas
    description: Requisitos previos para desarrollar con Store Framework
    event: issues.closed
    link: '{{ repoUrl }}/issues/1'
    actions:
      - type: respond
        with: new-issue.md
        issue: 1
        data:
          nextIssue: '2'
          nextName: 'Store Framework 101'
      - type: createIssue
        title: 'Store Framework 101'
        body: storeframework.md
  - title: Store Framework 101
    description: Definiciones rápidas e introductorias sobre Store Framework
    event: issues.closed
    link: '{{ repoUrl }}/issues/2'
    actions:
      - type: respond
        with: new-issue.md
        issue: 2
        data:
          nextIssue: '3'
          nextName: 'Funcionamiento del curso'
      - type: createIssue
        title: 'Funcionamiento del curso'
        body: course.md
  - title: Funcionamiento del curso
    description: Explicando cómo interactuar con el curso
    event: issues.closed
    link: '{{ repoUrl }}/issues/3'
    actions:
      - type: respond
        with: new-issue.md
        issue: 3
        data:
          nextIssue: '4'
          nextName: 'Hello, World!'
      - type: createIssue
        title: 'Hello, World!'
        body: helloworld.md
  - title: 'Hello, World!'
    description: Componga y haga referencia a su primer bloque en Store Framework
    event: status
    link: '{{ repoUrl }}/issues/4'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 4
        data:
          nextIssue: '5'
          nextName: 'Info Card: el call to action de Store Framework'
      - type: createIssue
        title: 'Info Card: el call to action de Store Framework'
        body: infocard.md
  - title: 'Info Card: el call to action de Store Framework'
    description: Definiremos un bloque call to action en nuestro home 
    event: status
    link: '{{ repoUrl }}/issues/5'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 5
        data:
          nextIssue: '6'
          nextName: 'CSS Handles y el poder de la personalización de bloques'
      - type: createIssue
        title: 'CSS Handles y el poder de la personalización de bloques'
        body: csshandles.md
  - title: 'CSS Handles y el poder de la personalización de bloques'
    description: Personalice el estilo de sus bloques
    event: status
    link: '{{ repoUrl }}/issues/6'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 6
        data:
          nextIssue: '7'
          nextName: 'Flex Layout: cree layouts utilizando el poder de Flexbox'
      - type: createIssue
        title: 'Flex Layout: cree layouts utilizando el poder de Flexbox'
        body: flexlayout.md
  - title: 'Flex Layout: cree layouts utilizando el poder de Flexbox'
    description: Creemos layouts complejos de forma sencilla
    event: status
    link: '{{ repoUrl }}/issues/7'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 7
        data:
          nextIssue: '8'
          nextName: Estante de productos
      - type: createIssue
        title: Estante de productos
        body: shelf.md
  - title: 'Estante de productos'
    description: Cómo mostrar una vitrina de productos de forma intuitiva
    event: status
    link: '{{ repoUrl }}/issues/8'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 8
        data:
          nextIssue: '9'
          nextName: Carrusel de bloques 
      - type: createIssue
        title: Carrusel de bloques
        body: slider.md
  - title: Carrusel de bloques
    description: Ingrese contenido en un layout de carrusel
    event: status
    link: '{{ repoUrl }}/issues/9'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 9
        data:
          nextIssue: '10'
          nextName: Haciendo que su contenido sea responsivo
      - type: createIssue
        title: Haciendo que su contenido sea responsivo
        body: responsive.md
  - title: Haciendo que su contenido sea responsivo
    description: Use responsive layout para adaptar su contenido a diferentes dispositivos
    event: status
    link: '{{ repoUrl }}/issues/10'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 10
        data:
          nextIssue: '11'
          nextName: Página de producto
      - type: createIssue
        title: Página de producto
        body: pdp.md
  - title: Página de producto
    description: Primeros pasos para crear una página de detalles de producto
    event: status
    link: '{{ repoUrl }}/issues/11'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 11
        data:
          nextIssue: '12'
          nextName: Evolucionando su página de producto (pdp)
      - type: createIssue
        title: Evolucionando su página de producto (pdp)
        body: pdp2.md
  - title: Evolucionando su página de producto (pdp)
    description: Agregando nuevos bloques y haciendo que la página sea más interactiva
    event: status
    link: '{{ repoUrl }}/issues/12'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 12
        data:
          nextIssue: '13'
          nextName: Finalizando su pdp
      - type: createIssue
        title: Finalizando su pdp
        body: pdp3.md
  - title: Finalizando su pdp
    description: Usando productos relacionados y alterando propiedades
    event: status
    link: '{{ repoUrl }}/issues/13'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 13
        data:
          nextIssue: '14'
          nextName: Página de búsqueda
      - type: createIssue
        title: Página de búsqueda
        body: search.md
  - title: Página de búsqueda
    description: Conociendo los bloques de una página de búsqueda
    event: status
    link: '{{ repoUrl }}/issues/14'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 14
        data:
          nextIssue: '15'
          nextName: Ajustando layout de página de búsqueda 
      - type: createIssue
        title: Ajustando layout de página de búsqueda 
        body: search2.md
  - title: Ajustando layout de página de búsqueda 
    description: Agregando líneas y columnas para mejorar el layout de búsqueda
    event: status
    link: '{{ repoUrl }}/issues/15'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 15
        data:
          nextIssue: '16'
          nextName: Estilos globales
      - type: createIssue
        title: Estilos globales
        body: styles.md
  - title: Estilos globales
    description: Altere clases semánticas para cambiar el estilo de su tienda
    event: status
    link: '{{ repoUrl }}/issues/16'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 16
        data:
          nextIssue: '17'
          nextName: Creando templates personalizados
      - type: createIssue
        title: Creando templates personalizados
        body: template.md
  - title: Creando templates personalizados
    description: Cree una ruta y asocie un template personalizado
    event: status
    link: '{{ repoUrl }}/issues/17'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 17
        data:
          nextIssue: '18'
          nextName: Layout de pestañas 
      - type: createIssue
        title: Layout de pestañas 
        body: tab-layout.md
  - title: Layout de pestañas 
    description: Usando layout de pestañas en la página institucional
    event: status
    link: '{{ repoUrl }}/issues/18'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 18
        data:
          nextIssue: '19'
          nextName: Explorando el poder de rich text
      - type: createIssue
        title: Explorando el poder de rich text
        body: richtextmarkdown.md
  - title: Explorando el poder de rich text
    description: Usando el lenguaje de Markdown de forma avanzada 
    event: status
    link: '{{ repoUrl }}/issues/19'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 19
        data:
          nextIssue: '20'
          nextName: Insertando un Iframe en nuestra página institucional
      - type: createIssue
        title: Insertando un Iframe en nuestra página institucional
        body: iframe.md
  - title: Insertando un Iframe en nuestra página institucional
    description: Mostrando una publicación de Instagram en su tienda
    event: status
    link: '{{ repoUrl }}/issues/20'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 20
        data:
          nextIssue: '21'
          nextName: Construyendo un landing personalizado de búsqueda 
      - type: createIssue
        title: Construyendo un landing personalizado de búsqueda 
        body: landing.md
  - title: Construyendo un landing personalizado de búsqueda 
    description: Definiendo páginas de eventos con productos personalizados
    event: status
    link: '{{ repoUrl }}/issues/21'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 21
        data:
          nextIssue: '22'
          nextName: Cabecera de la tienda
      - type: createIssue
        title: Cabecera de la tienda
        body: header.md
  - title: Cabecera de la tienda
    description: Definiendo bloques de cabecera y alterando iconografía
    event: status
    link: '{{ repoUrl }}/issues/22'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 22
        data:
          nextIssue: '23'
          nextName: Menú
      - type: createIssue
        title: Menú
        body: menu.md
  - title: Menú
    description: Creando la navegación de su tienda
    event: status
    link: '{{ repoUrl }}/issues/23'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 23
        data:
          nextIssue: '24'
          nextName: Menú avanzado con Flex Layout
      - type: createIssue
        title: Menú avanzado con Flex Layout
        body: menu-flex.md
  - title: Menú avanzado con Flex Layout
    description: Enriqueciendo el menú con otros bloques
    event: status
    link: '{{ repoUrl }}/issues/24'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 24
        data:
          nextIssue: '25'
          nextName: Pie de Página
      - type: createIssue
        title: Pie de Página
        body: footer.md
  - title: Pie de Página 
    description: Definiendo bloques de pie de página
    event: status
    link: '{{ repoUrl }}/issues/25'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success